# Generated by Django 5.0.6 on 2024-06-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usermood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermood',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
